### ISSUE TITLE
what the example data looks like

### ISSUE THREAD

**Issue by lwq-star** [ajwdewit/agera5tools#1]
Hello, 

i'm trying to use agera5 as a weather data input to the model! 
A few days ago I downloaded agera5 from the research area using the python package cdsapi. But I found out today that you have already developed one of these packages! 

In your example you seem to be working on data that has already been downloaded locally, but I don't know what the example data looks like, can you please provide the example data? 

And I would like to do an area-by-image simulation, how can this agera5tools package help me? 

Thank you very much for taking your valuable time to develop such a python package and a python implementation of the WOFOST model, they have helped me a lot!

**Comment by ajwdewit** [comment]
Hi, the agera5tools package indeed expects a certain structure that looks like below with all data in daily netCDF files. 

Al files have the following naming convention:

```
Temperature-Air-2m-Max-Day-Time_C3S-glob-agric_AgERA5_19791228_final-v1.0.nc
{-----variable name ----------}_C3S-glob-agric_AgERA5_{-date-}_final-v1.0.nc
```

I am still thinking of extending agera5tools with a download option that automatically puts the data in this structure, but so far I have not found the time to do so.

Allard


├── 1979
│   ├── Cloud-Cover-Mean
│   ├── Dew-Point-Temperature-2m-Mean
│   ├── Precipitation-Flux
│   ├── Precipitation-Rain-Duration-Fraction
│   ├── Precipitation-Solid-Duration-Fraction
│   ├── Relative-Humidity-2m-06h
│   ├── Relative-Humidity-2m-09h
│   ├── Relative-Humidity-2m-12h
│   ├── Relative-Humidity-2m-15h
│   ├── Relative-Humidity-2m-18h
│   ├── Snow-Thickness-LWE-Mean
│   ├── Snow-Thickness-Mean
│   ├── Solar-Radiation-Flux
│   ├── Temperature-Air-2m-Max-24h
│   ├── Temperature-Air-2m-Max-Day-Time
│   ├── Temperature-Air-2m-Mean-24h
│   ├── Temperature-Air-2m-Mean-Day-Time
│   ├── Temperature-Air-2m-Mean-Night-Time
│   ├── Temperature-Air-2m-Min-24h
│   ├── Temperature-Air-2m-Min-Night-Time
│   ├── Vapour-Pressure-Mean
│   └── Wind-Speed-10m-Mean
├── 1980
│   ├── Cloud-Cover-Mean
│   ├── Dew-Point-Temperature-2m-Mean
│   ├── Precipitation-Flux

**Comment by lwq-star** [comment]
Thank you and I look forward to your expansion!
I would like to offer you two examples here
https://github.com/paperoses/WOFOST_weather_file_generation/blob/main/AgERA5_download_for_WOFOST.py
https://github.com/Ewan82/ghana_data/blob/master/data_downloaders/era_downloader.py
Hope you find this helpful！

**Comment by lwq-star** [comment]
Excuse me, 

I have one more question, I have turned on the default global elevation data(grid_elevation_landfraction.nc), 
its spatial resolution is 0.1 degrees, but I do not know
 what data it comes from? 
Is the accuracy high? 
Can you briefly explain this?

**Comment by ajwdewit** [comment]
I will have to foreward your question to the colleague who developed it. But because of holidays this will take some time.

Allard



lwq-star ***@***.***> schreef op 23 juli 2022 15:15:48 CEST:
>Excuse me, 
>
>I have one more question, I have turned on the default global elevation data(grid_elevation_landfraction.nc), 
>its spatial resolution is 0.1 degrees, but I do not know
> what data it comes from? 
>Is the accuracy high? 
>Can you briefly explain this?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/ajwdewit/agera5tools/issues/1#issuecomment-1193124168
>You are receiving this because you commented.
>
>Message ID: ***@***.***>
-- 
Verstuurd vanaf mijn Android apparaat met K-9 Mail. Excuseer mijn beknoptheid.

**Comment by ajwdewit** [comment]
Is stil still relevant? 

Allard
