### ISSUE TITLE
sqlalchemy version issue caused db creation failed when init

### ISSUE THREAD

**Issue by frank0434** [ajwdewit/agera5tools#2]
**Problem**: 
sqlalchemy > 2.0 yield error message 
`sqlalchemy.exc.ArgumentError: expected schema argument to be a string, got <class 'sqlalchemy.engine.base.Engine'>.`

**Trial and error**：
Followed the documentation on sqlalchemy website about creating sqlite db https://docs.sqlalchemy.org/en/20/core/engines.html#sqlite

changed the `dsn` argument value into a string with double quote in the configuration file 
`dsn: "sqlite:///C:\\Users\\GitRepos\\DataGathering\\Climate\\agera5.db"`

Still not working 

Tried installing an older version followed the suggestion `https://github.com/Jacob-Stevens-Haas/tehom/issues/25#issuecomment-1630266724`

**WORKED**

So the **SOLUTION**

```
pip uninstall sqlalchemy 

pip install sqlalchemy<2.0 
```

Documentation: 
https://github.com/ajwdewit/agera5tools/edit/main/doc/user_guide.rst

**Comment by ajwdewit** [comment]
Hi, the requirements.txt and pyproject.toml files explicitly state SQLAlchemy < 2.0. So not sure how you ended up with SQLAlchemy = 2.0. I will have a look at the dsn arguments, maybe it is good to quote them explicitly and add an example for windows as well.

Allard

**Comment by frank0434** [comment]
thanks, Allard. I was following the documentation [website](https://agera5tools.readthedocs.io/en/latest/user_guide.html#initializing-agera5tools-part-i). It mentions `SQLAlchemy >= 1.4`, so  I used the default pip install without specifying the version number. 
Will reuse the requirement file next time, which would save lots of googling. 😄 .
