### ISSUE TITLE
writing to /tmp may not be permitted, add a config option to specify working directory

### ISSUE THREAD

**Issue by krsnapaudel** [ajwdewit/agera5tools#3]
In Google colab, the example code does not run because writing to /tmp is not permitted.
It would be good to allow the user to specify the working directory (e.g. $HOME/ager5tools).
In Google colab, this could /content/agera5tools.

**Comment by ajwdewit** [comment]
Before writing a new config file 2.0.11 modifies the agera5tools.yaml config file by setting all paths to the users home folder. So this should work on CoLab.
